version: '3.8'

services:

   db:
     image: mariadb
     volumes:
       - ./db_data:/var/lib/mysql:delegated
     restart: "no"
     ports:
       - "33033:3306"
     environment:
       MYSQL_ROOT_PASSWORD: drupalpass
       MYSQL_DATABASE: drupal
       MYSQL_USER: drupaluser
       MYSQL_PASSWORD: drupalpass

   drupal:
     depends_on:
       - db
     image: drupal
     volumes:
       - ./../Drupal/:/var/www/html:delegated
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:delegated
     ports:
       - "8033:80"
     restart: "no"
     environment:
       DB_HOST: db:3306
       DB_USER: drupaluser
       DB_PASSWORD: drupalpass
       DB_NAME: drupal

volumes:
    db_data:
    uploads.ini: